name: TagBot
on:
  schedule:
    - cron: 0 0 * * *
  issues: # I have added this line
    types: [opened, closed, reopened]
  workflow_dispatch:
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
